#!/usr/bin/env bash
# Configuring HAProxy

sudo apt-get update
sudo apt-get install -y haproxy
proxy_line="\n\nfrontend first_frontend\n\tbind :80,:8080\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver web-01 34.75.140.247\n\tserver web-02 54.198.208.252"
echo "$proxy_line" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
