#!/usr/bin/env bash
# Prints To infinity and beyond indefinitely, with a sleep 2, and is invincible to SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done

