#!/usr/bin/env bash
# Prints "Best School" 10 times using while, but prints different on 4 and 8

i=1
while [ $i -le 100 ]; do
    if ((i % 3 == 0 && i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i+=1))
done
