#!/usr/bin/env bash
# Configures an apache server

sudo apt update
sudo apt install -y apache2
sudo rm /var/www/html/*
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello Holberton" >> /var/www/html/index.html
service apache2 reload
