#!/usr/bin/env bash
# Changes nginx to execute as nginx user
# shellcheck disable=SC2046

sudo kill -9 $(pidof apache2)
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[\:\:\]\:80 default_server ipv6only=on;/listen \[\:\:\]\:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
